version: "3.3"

services:

  webdav:
    image: ugeek/webdav:amd64    
    container_name: webdav
    restart: unless-stopped
    volumes:
      - ./share:/media
    ports:
      - "8200:80"
    env_file: .env      
    environment:
      - TZ=Europe/Madrid
      - PUID=1000
      - PGID=1000

